" Generated by vim-plug
" Sat May  7 12:57:16 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['BufOnly.nvim'].commit = '30579c2851743b00c4547c324a16f2c1cfa5a41c'
silent! let g:plugs['LuaSnip'].commit = '8f2480d7a8c23c164429f2e4b487f28fc9a72d4b'
silent! let g:plugs['bufferline.nvim'].commit = 'e97a404bd7449ecebab243c796c1016c98397fc0'
silent! let g:plugs['cmp-buffer'].commit = 'd66c4c2d376e5be99db68d2362cd94d250987525'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'ebdfc204afb87f15ce3d3d3f5df0b8181443b5ba'
silent! let g:plugs['cmp_luasnip'].commit = 'd6f837f4e8fe48eeae288e638691b91b97d1737f'
silent! let g:plugs['defx-git'].commit = '324552fc652ed09e14a45485945b2e52eb04cbdc'
silent! let g:plugs['defx.nvim'].commit = 'c3417f30029c384c73aeccb1084f21c14b4bae45'
silent! let g:plugs['everforest'].commit = '7c5e520962a57f7cd42bb0b9eab268795375d26e'
silent! let g:plugs['gitsigns.nvim'].commit = '1d1f043acf025f919b8dd12bb672569109c7f099'
silent! let g:plugs['lspsaga.nvim'].commit = '65e9ca7fb147668ce3f7321f8d734ae9b754241c'
silent! let g:plugs['lualine.nvim'].commit = '016a20711ee595a11426f9c1f4ab3e04967df553'
silent! let g:plugs['nvim-autopairs'].commit = '784398a8f184431fd4329f20b0e4f52e87707bbd'
silent! let g:plugs['nvim-cmp'].commit = '13d64460cba64950aff41e230cc801225bd9a3e2'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-lsp-installer'].commit = '9f19922ecab471b30957b0d96879c9acc3fcf672'
silent! let g:plugs['nvim-lspconfig'].commit = 'ec7119b166b16e681f663fcbf16b7139b38172ae'
silent! let g:plugs['nvim-treesitter'].commit = 'f735498a645e1a2aca7a0cfdaa2d7f8cec543846'
silent! let g:plugs['nvim-ts-context-commentstring'].commit = '097df33c9ef5bbd3828105e4bee99965b758dc3f'
silent! let g:plugs['nvim-web-devicons'].commit = '4415d1aaa56f73b9c05795af84d625c610b05d3b'
silent! let g:plugs['plenary.nvim'].commit = '2a278c8a12a399e25b78a43ebcd4f3996cd4e4b6'
silent! let g:plugs['popup.nvim'].commit = 'b7404d35d5d3548a82149238289fa71f7f6de4ac'
silent! let g:plugs['telescope-fzf-native.nvim'].commit = '8ec164b541327202e5e74f99bcc5fe5845720e18'
silent! let g:plugs['telescope.nvim'].commit = '567ec85b157f1606b500a0f755181f284810a28e'
silent! let g:plugs['todo-comments.nvim'].commit = '98b1ebf198836bdc226c0562b9f906584e6c400e'
silent! let g:plugs['toggleterm.nvim'].commit = '981e207e17ecd8bf065b5b9201c1d6d2395e9338'
silent! let g:plugs['trouble.nvim'].commit = '20469be985143d024c460d95326ebeff9971d714'
silent! let g:plugs['vim-commentary'].commit = '627308e30639be3e2d5402808ce18690557e8292'
silent! let g:plugs['vim-fugitive'].commit = 'c29ef11cd6478da675678265e76f9e527843876f'
silent! let g:plugs['vim-surround'].commit = 'baf89ad26488f6a7665d51b986f5c7ad2d22b30b'
silent! let g:plugs['vim-test'].commit = '0422b7fa087eb7dd1270dfcb1f3d634b57829b6e'

PlugUpdate!

