" Generated by vim-plug
" Sat May  7 13:26:11 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['BufOnly.nvim'].commit = '30579c2851743b00c4547c324a16f2c1cfa5a41c'
silent! let g:plugs['LuaSnip'].commit = 'cc0086390c6cd2eaebae1834b115c891649ec95f'
silent! let g:plugs['bufferline.nvim'].commit = 'e97a404bd7449ecebab243c796c1016c98397fc0'
silent! let g:plugs['cmp-buffer'].commit = 'd66c4c2d376e5be99db68d2362cd94d250987525'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'e6b5feb2e6560b61f31c756fb9231a0d7b10c73d'
silent! let g:plugs['cmp_luasnip'].commit = 'a9de941bcbda508d0a45d28ae366bb3f08db2e36'
silent! let g:plugs['defx-git'].commit = '324552fc652ed09e14a45485945b2e52eb04cbdc'
silent! let g:plugs['defx.nvim'].commit = 'fd5f9416d6acc908660ccca0799109a9a4f0a2d2'
silent! let g:plugs['everforest'].commit = 'f748681a3fac2496aedf694f5bd09a30f80cd3c0'
silent! let g:plugs['gitsigns.nvim'].commit = '0beb1941641bd7d5d7072d3612ee47c0eb80b63d'
silent! let g:plugs['lspsaga.nvim'].commit = '8dde091a61ab07f639baaa82b456d3508d0aa7e8'
silent! let g:plugs['lualine.nvim'].commit = '619ededcff79e33a7e0ea677881dd07957449f9d'
silent! let g:plugs['nvim-autopairs'].commit = 'aea913109d30c87df329ec9b8fea9aed6ef9f52a'
silent! let g:plugs['nvim-cmp'].commit = 'f81bfee10909e39c82ccd230f6f997438b16092e'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-lsp-installer'].commit = '6f82a174709c2767281916d02e2cac1d7a6dba6e'
silent! let g:plugs['nvim-lspconfig'].commit = '2f37b2ca07a3f89e7994b3b7f54c997e2cb3400a'
silent! let g:plugs['nvim-treesitter'].commit = '868053edf587fd6f07111428b65cbd23144da860'
silent! let g:plugs['nvim-ts-context-commentstring'].commit = '88343753dbe81c227a1c1fd2c8d764afb8d36269'
silent! let g:plugs['nvim-web-devicons'].commit = 'bdd43421437f2ef037e0dafeaaaa62b31d35ef2f'
silent! let g:plugs['plenary.nvim'].commit = '9069d14a120cadb4f6825f76821533f2babcab92'
silent! let g:plugs['popup.nvim'].commit = 'b7404d35d5d3548a82149238289fa71f7f6de4ac'
silent! let g:plugs['telescope-fzf-native.nvim'].commit = '281b07a5cba2dc255e2a35d3fa6e49af0c8cb37f'
silent! let g:plugs['telescope.nvim'].commit = '4681dcdffe20e1f23b6b9ccf28836537ed166c47'
silent! let g:plugs['todo-comments.nvim'].commit = '98b1ebf198836bdc226c0562b9f906584e6c400e'
silent! let g:plugs['toggleterm.nvim'].commit = '981e207e17ecd8bf065b5b9201c1d6d2395e9338'
silent! let g:plugs['trouble.nvim'].commit = '691d490cc4eadc430d226fa7d77aaa84e2e0a125'
silent! let g:plugs['vim-commentary'].commit = '3654775824337f466109f00eaf6759760f65be34'
silent! let g:plugs['vim-fugitive'].commit = 'b7287bd5421da62986d9abf9131509b2c9f918e4'
silent! let g:plugs['vim-surround'].commit = 'bf3480dc9ae7bea34c78fbba4c65b4548b5b1fea'
silent! let g:plugs['vim-test'].commit = '2240d7a4b868cb594b7d83544e1b6db4df806e5e'

PlugUpdate!

